#!/usr/bin/sh

sxhkd &
compton &
polybar example &

feh --bg-scale /home/victor/Imágenes/wallpapers/fondo.jpg /home/victor/Imágenes/wallpapers/MR_8.png


#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave-browser desktop=5
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
